name: Docker Android CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/*'
      - 'deps/*'
      - 'keys/*'
      - 'scripts/*'

jobs:
  build-api-33:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Docker image with Android 33
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: halimqarroum/docker-android:api-33
          build-args: API_LEVEL=33

  # build-api-32:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     - name: Build Docker image with Android 32
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: halimqarroum/docker-android:api-32
  #         build-args: API_LEVEL=32
  
  # build-api-31:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     - name: Build Docker image with Android 31
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: halimqarroum/docker-android:api-31
  #         build-args: API_LEVEL=31
  
  # build-api-30:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     - name: Build Docker image with Android 30
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: halimqarroum/docker-android:api-30
  #         build-args: API_LEVEL=30

  # build-api-29:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     - name: Build Docker image with Android 29
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: halimqarroum/docker-android:api-29
  #         build-args: API_LEVEL=29

  # build-api-28:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     - name: Build Docker image with Android 28
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: halimqarroum/docker-android:api-28
  #         build-args: |
  #           "API_LEVEL=28"
  #           "ARCHITECTURE=x86"
  
  # build-api-28-playstore:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     - name: Build Docker image with Android 28 and the PlayStore
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: halimqarroum/docker-android:api-28-playstore
  #         build-args: |
  #           "API_LEVEL=28"
  #           "ARCHITECTURE=x86"
  #           "IMG_TYPE=google_apis_playstore"

  # build-minimal:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     - name: Build minimal Docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: halimqarroum/docker-android:minimal
  #         build-args: INSTALL_ANDROID_SDK=0
